// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PilatesStudio.Data;

#nullable disable

namespace PilatesStudio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604155049_aggiuntaColoreCorsi")]
    partial class aggiuntaColoreCorsi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PilatesStudio.Models.Abbonamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LezioniIncluse")
                        .HasColumnType("integer");

                    b.Property<int>("LezioniUtilizzate")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stato")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Abbonamenti");
                });

            modelBuilder.Entity("PilatesStudio.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Utenti", (string)null);
                });

            modelBuilder.Entity("PilatesStudio.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cap")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataNascita")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentoContrattoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirmaPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FotoProfiloPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UltimoAggiornamento")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("PilatesStudio.Models.EmailNotificaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErroreDettaglio")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InviatoAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Oggetto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stato")
                        .HasColumnType("integer");

                    b.Property<int>("TentativiEffettuati")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmailNotificaLog");
                });

            modelBuilder.Entity("PilatesStudio.Models.Insegnante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccountAttivato")
                        .HasColumnType("boolean");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAttivazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatoContratto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitoloDiStudio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UltimoAggiornamento")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("CodiceFiscale")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Insegnanti");
                });

            modelBuilder.Entity("PilatesStudio.Models.IscrizioneCorso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TipologiaCorsoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipologiaCorsoId", "ClienteId")
                        .IsUnique();

                    b.ToTable("IscrizioniCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.OccorrenzaCorso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataAnnullamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MotivoAnnullamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeSpan>("OraFine")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("OraInizio")
                        .HasColumnType("interval");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipologiaCorsoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaCorsoId", "Data", "OraInizio")
                        .IsUnique();

                    b.ToTable("OccorrenzeCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.PresenzaCorso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OccorrenzaCorsoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.Property<string>("RegistrataDa")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("OccorrenzaCorsoId", "ClienteId")
                        .IsUnique();

                    b.ToTable("PresenzeCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.SessioneCorso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GiornoSettimana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("OraFine")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("OraInizio")
                        .HasColumnType("interval");

                    b.Property<int>("TipologiaCorsoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaCorsoId");

                    b.ToTable("SessioniCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.TipologiaCorso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archiviato")
                        .HasColumnType("boolean");

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean");

                    b.Property<int>("CapacitaMax")
                        .HasColumnType("integer");

                    b.Property<string>("Colore")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime?>("DataArchiviazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UltimoAggiornamento")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TipologieCorsi");
                });

            modelBuilder.Entity("PilatesStudio.Models.TipologiaCorsoInsegnante", b =>
                {
                    b.Property<int>("TipologiaCorsoId")
                        .HasColumnType("integer");

                    b.Property<int>("InsegnanteId")
                        .HasColumnType("integer");

                    b.HasKey("TipologiaCorsoId", "InsegnanteId");

                    b.HasIndex("InsegnanteId");

                    b.ToTable("TipologieCorsoInsegnanti");
                });

            modelBuilder.Entity("PilatesStudio.Models.TokenAttivazioneAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataUtilizzo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ScadenzaUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Utilizzato")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ApplicationUserId", "Utilizzato");

                    b.ToTable("TokenAttivazioneAccount");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PilatesStudio.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PilatesStudio.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PilatesStudio.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PilatesStudio.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PilatesStudio.Models.Abbonamento", b =>
                {
                    b.HasOne("PilatesStudio.Models.Cliente", "Cliente")
                        .WithMany("Abbonamenti")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PilatesStudio.Models.Insegnante", b =>
                {
                    b.HasOne("PilatesStudio.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("PilatesStudio.Models.Insegnante", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PilatesStudio.Models.IscrizioneCorso", b =>
                {
                    b.HasOne("PilatesStudio.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PilatesStudio.Models.TipologiaCorso", "TipologiaCorso")
                        .WithMany("Iscrizioni")
                        .HasForeignKey("TipologiaCorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipologiaCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.OccorrenzaCorso", b =>
                {
                    b.HasOne("PilatesStudio.Models.TipologiaCorso", "TipologiaCorso")
                        .WithMany("Occorrenze")
                        .HasForeignKey("TipologiaCorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipologiaCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.PresenzaCorso", b =>
                {
                    b.HasOne("PilatesStudio.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PilatesStudio.Models.OccorrenzaCorso", "OccorrenzaCorso")
                        .WithMany("Presenze")
                        .HasForeignKey("OccorrenzaCorsoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("OccorrenzaCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.SessioneCorso", b =>
                {
                    b.HasOne("PilatesStudio.Models.TipologiaCorso", "TipologiaCorso")
                        .WithMany("Sessioni")
                        .HasForeignKey("TipologiaCorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipologiaCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.TipologiaCorsoInsegnante", b =>
                {
                    b.HasOne("PilatesStudio.Models.Insegnante", "Insegnante")
                        .WithMany()
                        .HasForeignKey("InsegnanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PilatesStudio.Models.TipologiaCorso", "TipologiaCorso")
                        .WithMany("TipologieCorsoInsegnanti")
                        .HasForeignKey("TipologiaCorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insegnante");

                    b.Navigation("TipologiaCorso");
                });

            modelBuilder.Entity("PilatesStudio.Models.TokenAttivazioneAccount", b =>
                {
                    b.HasOne("PilatesStudio.Models.ApplicationUser", "Utente")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("PilatesStudio.Models.Cliente", b =>
                {
                    b.Navigation("Abbonamenti");
                });

            modelBuilder.Entity("PilatesStudio.Models.OccorrenzaCorso", b =>
                {
                    b.Navigation("Presenze");
                });

            modelBuilder.Entity("PilatesStudio.Models.TipologiaCorso", b =>
                {
                    b.Navigation("Iscrizioni");

                    b.Navigation("Occorrenze");

                    b.Navigation("Sessioni");

                    b.Navigation("TipologieCorsoInsegnanti");
                });
#pragma warning restore 612, 618
        }
    }
}
